<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;

class IngredientsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('ingredients')->insert([
            ['uuid' => (string) Str::uuid(),
             'name' => 'じゃがいも(メークイン)',
             'seasonality' => json_encode([9, 10, 11, 12]),
             'price' => 198,
             'unit' => '個',
             'image_path' => 'ingredients/me-kuin.jpg',
             'created_at' => now(),
             'updated_at' => now(),
            ],
            ['uuid' => (string) Str::uuid(),
             'name' => 'にんじん',
             'seasonality' => json_encode([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]),
             'price' => 98,
             'unit' => '本',
             'image_path' => 'ingredients/ninjin.jpg',
             'created_at' => now(),
             'updated_at' => now(),
            ],
            ['uuid' => (string) Str::uuid(),
             'name' => '玉ねぎ',
             'seasonality' => json_encode([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]),
             'price' => 98,
             'unit' => '個',
             'image_path' => 'ingredients/tamanegi.jpg',
             'created_at' => now(),
             'updated_at' => now(),
            ],
            ['uuid' => (string) Str::uuid(),
             'name' => '豚肉こま切れ',
             'seasonality' => json_encode([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]),
             'price' => 198,
             'unit' => 'g',
             'image_path' => 'ingredients/butakoma.jpg',
             'created_at' => now(),
             'updated_at' => now(),
            ],
            ['uuid' => (string) Str::uuid(),
             'name' => 'しょうゆ',
             'seasonality' => json_encode([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]),
             'price' => 268,
             'unit' => 'ml',
             'image_path' => 'ingredients/syouyu.jpg',
             'created_at' => now(),
             'updated_at' => now(),
            ],
            ['uuid' => (string) Str::uuid(),
             'name' => 'みりん',
             'seasonality' => json_encode([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]),
             'price' => 198,
             'unit' => 'ml',
             'image_path' => 'ingredients/mirin.jpg',
             'created_at' => now(),
             'updated_at' => now(),
            ],
            ['uuid' => (string) Str::uuid(),
             'name' => '砂糖',
             'seasonality' => json_encode([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]),
             'price' => 98,
             'unit' => 'g',
             'image_path' => 'ingredients/sato.jpg',
             'created_at' => now(),
             'updated_at' => now(),
            ],
            ['uuid' => (string) Str::uuid(),
             'name' => 'しらたき',
             'seasonality' => json_encode([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]),
             'price' => 98,
             'unit' => '袋',
             'image_path' => 'ingredients/sirataki.jpg',
             'created_at' => now(),
             'updated_at' => now(),
            ],
            ['uuid' => (string) Str::uuid(),
             'name' => 'インゲン',
             'seasonality' => json_encode([6, 7, 8, 9]),
             'price' => 398,
             'unit' => 'パック',
             'image_path' => 'ingredients/ingen.jpg',
             'created_at' => now(),
             'updated_at' => now(),
            ],
            ['uuid' => (string) Str::uuid(),
            'name' => 'ほんだし',
            'seasonality' => json_encode([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]),
            'price' => 376,
            'unit' => '箱',
            'image_path' => 'ingredients/hondashi.png',
            'created_at' => now(),
            'updated_at' => now(),
            ],
            ['uuid' => (string) Str::uuid(),
            'name' => '料理酒',
            'seasonality' => json_encode([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]),
            'price' => 360,
            'unit' => 'ml',
            'image_path' => 'ingredients/ryourisyu.png',
            'created_at' => now(),
            'updated_at' => now(),
            ],
            ['uuid' => (string) Str::uuid(),
            'name' => '塩',
            'seasonality' => json_encode([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]),
            'price' => 321,
            'unit' => 'kg',
            'image_path' => 'ingredients/sio.jpg',
            'created_at' => now(),
            'updated_at' => now(),
            ],
            ['uuid' => (string) Str::uuid(),
            'name' => '水',
            'seasonality' => json_encode([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]),
            'price' => 0,
            'unit' => 'ml',
            'image_path' => null,
            'created_at' => now(),
            'updated_at' => now(),
            ],
        ]);
    }
}
